spring:
  application:
    name: CampusExpenseManagement
  liquibase:
    enabled: true
    change-log: db/master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/campusExpense
    username: postgres
    password: dothang3z
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 5