DROP TABLE IF EXISTS public.users CASCADE;
CREATE TABLE public.users
(
    "id"         int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 5 CACHE 1 NO CYCLE),
    "userName"   VARCHAR(100),
    "password"   VARCHAR(100),
    "first_name" varchar(100),
    "last_name"  varchar(100),
    "email"      varchar(150),
    "created_at" timestamp,
    "updated_at" timestamp,
    "deleted_at" timestamp,

    CONSTRAINT users_action_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.accounts CASCADE;
CREATE TABLE public.accounts
(
    "id"         int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 5 CACHE 1 NO CYCLE),
    "role"    varchar(100),
    "user_id" int8,

    CONSTRAINT accounts_action_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.categories CASCADE;
CREATE TABLE public.categories
(
    "id"         int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 5 CACHE 1 NO CYCLE),
    "name"        varchar(255),
    "description" text,
    CONSTRAINT categories_action_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.banks CASCADE;
CREATE TABLE public.banks
(
    "id"             int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 5 CACHE 1 NO CYCLE),
    "name"           varchar(150),
    "account_number" varchar(20),
    "account_type"   varchar(100),
    "amount"         decimal(10, 2),
    "created_at"     timestamp,
    "updated_at"     timestamp,
    "deleted_at"     timestamp,
    CONSTRAINT banks_action_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.transactions CASCADE;
CREATE TABLE public.transactions
(
    "id"             int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 5 CACHE 1 NO CYCLE),
    "user_id"        int8,
    "payment_method" varchar(100),
    "bank_id"        int8,
    "amount"         DECIMAL(10, 2),
    "date"           timestamp,
    "status"         varchar(50),
    CONSTRAINT transactions_action_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.expenses CASCADE;
CREATE TABLE public.expenses
(
    "id"             int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 5 CACHE 1 NO CYCLE),
    "name"           varchar(225),
    "user_id"        int8,
    "amount"         DECIMAL(10, 2),
    "description"    TEXT,
    "category_id"    int8,
    "transaction_id" int8,
    "date"           timestamp,
    CONSTRAINT expenses_action_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.budgets CASCADE;
CREATE TABLE public.budgets
(
    "id"         int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 5 CACHE 1 NO CYCLE),
    "category_id" int8,
    "user_id"     int8,
    "amount"      decimal(10, 2),
    "date_start"  timestamp,
    "date_end"    timestamp,
    "status"      varchar(100),
    CONSTRAINT budgets_action_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.payments CASCADE;
CREATE TABLE public.payments
(
    "id"             int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 5 CACHE 1 NO CYCLE),
    "transaction_id" int8,
    "amount"         decimal(10, 2),
    "date"           timestamp,
    "payment_method" varchar(150),
    "status"         varchar(150),
    CONSTRAINT payments_action_pkey PRIMARY KEY (id)
);

ALTER TABLE public.accounts
    ADD CONSTRAINT fk_user_id FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE public.transactions
    ADD CONSTRAINT fk_user_id FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE public.transactions
    ADD CONSTRAINT fk_bank_id FOREIGN KEY ("bank_id") REFERENCES "banks" ("id");

ALTER TABLE public.expenses
    ADD CONSTRAINT fk_user_id FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE public.expenses
    ADD CONSTRAINT fk_category_id FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE public.expenses
    ADD CONSTRAINT fk_transaction_id FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id");

ALTER TABLE public.budgets
    ADD CONSTRAINT fk_category_id FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE public.budgets
    ADD CONSTRAINT fk_user_id FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE public.payments
    ADD CONSTRAINT fk_transaction_id FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id");
